# Generated by Django 6.0.3 on 2026-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbudget',
            name='current',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userbudget',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
